FROM ubuntu:22.04

COPY ./deb-files/backend-flo_0.15.1.1-satoshilabs-1_amd64.deb /opt/backend.deb

RUN apt update && apt install -y /opt/backend.deb
WORKDIR /opt/coins/nodes/flo
RUN sed -i 's/daemon=1/daemon=0/' /opt/coins/nodes/flo/flo.conf

ENTRYPOINT ["/opt/coins/nodes/flo/bin/flod", "-datadir=/opt/coins/data/flo/backend", "-conf=/opt/coins/nodes/flo/flo.conf", "-pid=/run/flo/flo.pid"]
