version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8066:8066"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.blockbook
    ports:
      - "9166:9166"
      - "9066:9066"  
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8066
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

